# Generated by Django 5.2.7 on 2025-10-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ID_Proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Proveedor', models.CharField(max_length=100)),
                ('Contacto_Nombre', models.CharField(max_length=100)),
                ('Contacto_Telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('Contacto_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Direccion_Proveedor', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['Nombre_Proveedor'],
            },
        ),
    ]
